"""Localized labels for the map camera HUD.

These strings are baked into the rendered PNG with PIL, so — unlike entity or
config strings — they cannot live in Home Assistant's ``strings.json`` /
``translations/*.json`` files: hassfest only accepts the known translation
categories there, and a custom one would fail the (blocking) manifest check.

Instead this in-code table is selected by the Home Assistant UI language. The
English entry is complete and is used both as the fallback for any missing key
and for any language not listed here, so a render never shows a blank label.
"""

from __future__ import annotations

# English is the source of truth: every key that the HUD renders must exist
# here. Other languages may be partial; missing keys fall back to English.
HUD_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "waiting": "Waiting for map data…",
        "empty_subtitle": "Map metadata received, but there are no spatial points to draw",
        "snapshot": "Map Snapshot",
        "updated": "Updated",
        "lbl_map": "Map",
        "lbl_area": "Area",
        "lbl_mode": "Mode",
        "lbl_size": "Size",
        "lbl_origin": "Origin",
        "lbl_backup": "Backup",
        "lbl_flags": "Flags",
        "flag_adv_edge": "Adv Edge",
        "flag_locked": "Locked",
        "flag_unlocked": "Unlocked",
        "flag_build_on": "Build Map",
        "flag_build_off": "Build Off",
        "backup_off": "Off",
        "backup_item": "item",
        "nogo": "No-go",
        "pass_short": "Pass",
        "pass_through": "Pass-through",
        "tunnel": "Tunnel",
        "required": "Required",
        "obstacle": "Obstacle",
        "path": "Path",
        "coverage": "Coverage",
    },
    "de": {
        "waiting": "Warte auf Kartendaten …",
        "empty_subtitle": "Karten-Metadaten empfangen, aber keine Geometriepunkte zum Zeichnen",
        "snapshot": "Karten-Schnappschuss",
        "updated": "Aktualisiert",
        "lbl_map": "Karte",
        "lbl_area": "Fläche",
        "lbl_mode": "Modus",
        "lbl_size": "Größe",
        "lbl_origin": "Ursprung",
        "lbl_backup": "Backup",
        "lbl_flags": "Status",
        "flag_adv_edge": "Erw. Kante",
        "flag_locked": "Gesperrt",
        "flag_unlocked": "Frei",
        "flag_build_on": "Kartierung",
        "flag_build_off": "Keine Kart.",
        "backup_off": "Aus",
        "backup_item": "Stk.",
        "nogo": "Sperrzone",
        "pass_short": "Durchf.",
        "pass_through": "Durchfahrt",
        "tunnel": "Tunnel",
        "required": "Pflicht",
        "obstacle": "Hindernis",
        "path": "Pfad",
        "coverage": "Abdeckung",
    },
    "fr": {
        "waiting": "En attente des données de carte …",
        "empty_subtitle": "Métadonnées de carte reçues, mais aucun point géométrique à dessiner",
        "snapshot": "Aperçu de la carte",
        "updated": "Mis à jour",
        "lbl_map": "Carte",
        "lbl_area": "Surface",
        "lbl_mode": "Mode",
        "lbl_size": "Taille",
        "lbl_origin": "Origine",
        "lbl_backup": "Sauvegarde",
        "lbl_flags": "État",
        "flag_adv_edge": "Bord avancé",
        "flag_locked": "Verrouillé",
        "flag_unlocked": "Déverrouillé",
        "flag_build_on": "Cartographie",
        "flag_build_off": "Sans cartog.",
        "backup_off": "Non",
        "backup_item": "élément",
        "nogo": "Interdit",
        "pass_short": "Passage",
        "pass_through": "Passage",
        "tunnel": "Tunnel",
        "required": "Requis",
        "obstacle": "Obstacle",
        "path": "Trajet",
        "coverage": "Couverture",
    },
    "es": {
        "waiting": "Esperando datos del mapa …",
        "empty_subtitle": "Metadatos del mapa recibidos, pero no hay puntos geométricos para dibujar",
        "snapshot": "Instantánea del mapa",
        "updated": "Actualizado",
        "lbl_map": "Mapa",
        "lbl_area": "Área",
        "lbl_mode": "Modo",
        "lbl_size": "Tamaño",
        "lbl_origin": "Origen",
        "lbl_backup": "Copia",
        "lbl_flags": "Estado",
        "flag_adv_edge": "Borde avanz.",
        "flag_locked": "Bloqueado",
        "flag_unlocked": "Desbloq.",
        "flag_build_on": "Mapeo",
        "flag_build_off": "Sin mapeo",
        "backup_off": "No",
        "backup_item": "elem.",
        "nogo": "Prohibido",
        "pass_short": "Paso",
        "pass_through": "Paso",
        "tunnel": "Túnel",
        "required": "Requerido",
        "obstacle": "Obstáculo",
        "path": "Ruta",
        "coverage": "Cobertura",
    },
    "it": {
        "waiting": "In attesa dei dati della mappa …",
        "empty_subtitle": "Metadati della mappa ricevuti, ma nessun punto geometrico da disegnare",
        "snapshot": "Istantanea della mappa",
        "updated": "Aggiornato",
        "lbl_map": "Mappa",
        "lbl_area": "Area",
        "lbl_mode": "Modalità",
        "lbl_size": "Dimensione",
        "lbl_origin": "Origine",
        "lbl_backup": "Backup",
        "lbl_flags": "Stato",
        "flag_adv_edge": "Bordo avanz.",
        "flag_locked": "Bloccato",
        "flag_unlocked": "Sbloccato",
        "flag_build_on": "Mappatura",
        "flag_build_off": "No mappat.",
        "backup_off": "No",
        "backup_item": "elem.",
        "nogo": "Divieto",
        "pass_short": "Passaggio",
        "pass_through": "Passaggio",
        "tunnel": "Tunnel",
        "required": "Richiesto",
        "obstacle": "Ostacolo",
        "path": "Percorso",
        "coverage": "Copertura",
    },
    "nl": {
        "waiting": "Wachten op kaartgegevens …",
        "empty_subtitle": "Kaartmetadata ontvangen, maar geen geometrische punten om te tekenen",
        "snapshot": "Kaartmomentopname",
        "updated": "Bijgewerkt",
        "lbl_map": "Kaart",
        "lbl_area": "Oppervlak",
        "lbl_mode": "Modus",
        "lbl_size": "Grootte",
        "lbl_origin": "Oorsprong",
        "lbl_backup": "Back-up",
        "lbl_flags": "Status",
        "flag_adv_edge": "Rand geav.",
        "flag_locked": "Vergrend.",
        "flag_unlocked": "Ontgrend.",
        "flag_build_on": "Kartering",
        "flag_build_off": "Geen kart.",
        "backup_off": "Uit",
        "backup_item": "item",
        "nogo": "Verboden",
        "pass_short": "Doorgang",
        "pass_through": "Doorgang",
        "tunnel": "Tunnel",
        "required": "Vereist",
        "obstacle": "Obstakel",
        "path": "Pad",
        "coverage": "Dekking",
    },
    "pt": {
        "waiting": "À espera dos dados do mapa …",
        "empty_subtitle": "Metadados do mapa recebidos, mas não há pontos geométricos para desenhar",
        "snapshot": "Instantâneo do mapa",
        "updated": "Atualizado",
        "lbl_map": "Mapa",
        "lbl_area": "Área",
        "lbl_mode": "Modo",
        "lbl_size": "Tamanho",
        "lbl_origin": "Origem",
        "lbl_backup": "Backup",
        "lbl_flags": "Estado",
        "flag_adv_edge": "Borda avanç.",
        "flag_locked": "Bloqueado",
        "flag_unlocked": "Desbloq.",
        "flag_build_on": "Mapeamento",
        "flag_build_off": "Sem mapeam.",
        "backup_off": "Não",
        "backup_item": "item",
        "nogo": "Proibido",
        "pass_short": "Passagem",
        "pass_through": "Passagem",
        "tunnel": "Túnel",
        "required": "Necessário",
        "obstacle": "Obstáculo",
        "path": "Trajeto",
        "coverage": "Cobertura",
    },
    "zh-Hans": {
        "waiting": "正在等待地图数据…",
        "empty_subtitle": "已接收地图元数据，但没有可绘制的空间点",
        "snapshot": "地图快照",
        "updated": "更新于",
        "lbl_map": "地图",
        "lbl_area": "面积",
        "lbl_mode": "模式",
        "lbl_size": "尺寸",
        "lbl_origin": "原点",
        "lbl_backup": "备份",
        "lbl_flags": "状态",
        "flag_adv_edge": "精修边缘",
        "flag_locked": "已锁定",
        "flag_unlocked": "未锁定",
        "flag_build_on": "可建图",
        "flag_build_off": "不可建图",
        "backup_off": "关闭",
        "backup_item": "项",
        "nogo": "禁区",
        "pass_short": "可穿行",
        "pass_through": "可穿行区",
        "tunnel": "通道",
        "required": "必割区",
        "obstacle": "障碍",
        "path": "路径",
        "coverage": "覆盖",
    },
    "zh-Hant": {
        "waiting": "正在等待地圖資料…",
        "empty_subtitle": "已接收地圖中繼資料，但沒有可繪製的空間點",
        "snapshot": "地圖快照",
        "updated": "更新於",
        "lbl_map": "地圖",
        "lbl_area": "面積",
        "lbl_mode": "模式",
        "lbl_size": "尺寸",
        "lbl_origin": "原點",
        "lbl_backup": "備份",
        "lbl_flags": "狀態",
        "flag_adv_edge": "精修邊緣",
        "flag_locked": "已鎖定",
        "flag_unlocked": "未鎖定",
        "flag_build_on": "可建圖",
        "flag_build_off": "不可建圖",
        "backup_off": "關閉",
        "backup_item": "項",
        "nogo": "禁區",
        "pass_short": "可穿行",
        "pass_through": "可穿行區",
        "tunnel": "通道",
        "required": "必割區",
        "obstacle": "障礙",
        "path": "路徑",
        "coverage": "覆蓋",
    },
}


def resolve_language(raw: str | None) -> str:
    """Map a Home Assistant language code to a HUD_STRINGS key.

    Exact matches win (``zh-Hans``); otherwise the base subtag is tried
    (``pt-BR`` -> ``pt``, ``de-DE`` -> ``de``). Any Chinese variant resolves to
    simplified unless it is explicitly traditional. Everything else -> English.
    """
    if not isinstance(raw, str) or not raw:
        return "en"
    if raw in HUD_STRINGS:
        return raw
    lowered = raw.lower()
    base = lowered.split("-")[0]
    if base == "zh":
        if "hant" in lowered or lowered in ("zh-tw", "zh-hk", "zh-mo"):
            return "zh-Hant"
        return "zh-Hans"
    if base in HUD_STRINGS:
        return base
    return "en"


def hud_strings(raw: str | None) -> dict[str, str]:
    """Return a complete label map for the language, English-filled."""
    lang = resolve_language(raw)
    if lang == "en":
        return dict(HUD_STRINGS["en"])
    return {**HUD_STRINGS["en"], **HUD_STRINGS[lang]}
